# This is a config for E2B sandbox template.
# You can use template ID (tq7jiookeift177lbszk) or template name (some-nextjs-test-3) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox.create("some-nextjs-test-3") # Sync sandbox
# sandbox = await AsyncSandbox.create("some-nextjs-test-3") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('some-nextjs-test-3')

team_id = "6f1d5037-7d06-47be-8cfb-10a87942c9a1"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "some-nextjs-test-3"
template_id = "tq7jiookeift177lbszk"
